### ISSUE TITLE
安装中文后无法更改设置

### ISSUE THREAD

**Issue by fengsuiyvmin** [zetaloop/IDLE-CN#2]
Python3.12.6版本，Windows11环境下，在[设置]-[IDLE设置]菜单中，更改设置后点击[确定]和[应用]无反应。

**Comment by zetaloop** [comment]
可以重现，正在排查问题

**Comment by zetaloop** [comment]
是中文输入法误触问题的修复造成的，它阻止了Fn快捷键的注册，但是没有阻止快捷键的解除，导致设置无法应用。

v1.2.0 已解决。
